web/router.ex
defmodule RoomPlz.Router do
  use RoomPlz.Web, :router
  use Coherence.Router
  alias RoomPlz.Branch

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
    plug :get_other_branches
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
    plug :get_other_branches
  end

  scope "/" do
    pipe_through :browser
    coherence_routes
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug Coherence.Authentication.Session
  end

  pipeline :api_protected do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
  end

  scope "/", RoomPlz do
    pipe_through :protected # protected resources

    resources "/users", UserController do
      get "/requests", UserController, :user_requests
    end

    resources "/branches", BranchController do
      resources "/events", EventController
      resources "/rooms", RoomController
    end
    get "/event_logs", EventLogController, :index

    # Car Booking
    resources "/cars", CarController
    get "/car_logs", CarController, :show_car_logs

    resources "/slots", SlotController, except: [:show]
    get "/slot_logs", SlotLogController, :index

    # Authorization
    get "/auth/google", AuthController, :gg_authenticate
    get "/auth/google/callback", AuthController, :gg_callback
    delete "/auth/google", AuthController, :gg_delete

  end

  scope "/", RoomPlz do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/teams", TeamController
    get"/slots/:id", SlotController,  :show
    get "/rooms/suggestion", RoomController, :suggestion

    resources "/branches", BranchController, only: [:show] do
      get "/calendar", CalendarController, :index
    end
    # Car Booking
    get "/car_calendar", CarController, :show_car_calendar

    # Authorization
    get "/auth/wsm", AuthController, :wsm_authenticate
    get "/auth/wsm/callback", AuthController, :wsm_callback
  end

  scope "/api", RoomPlz do
    pipe_through :api

    get "/rooms", APIController, :rooms
    get "/branches/:id", APIController, :show_branch
    get "/suggestion", APIController, :suggestion

    # Car Booking
    get "/cars", APIController, :cars
    get "/slots", APIController, :slots
    get "/slot/:id", APIController, :get_slot
  end

  scope "/api", RoomPlz do
    pipe_through :api_protected

    get "/users", APIController, :users
    get "/users/:id", APIController, :get_invitation_list
    post "/events/synchronize", APIController, :synchronize
    post "/import_events", APIController, :import_events
  end

  defp get_other_branches(conn, _params) do
    branch_id = if conn.params["branch_id"], do: String.to_integer(conn.params["branch_id"])
    assign(conn, :other_branches, Branch.get_other_branches(branch_id))
  end
end

web/models/coherence/user.ex
defmodule RoomPlz.User do
  use RoomPlz.Web, :model
  use Coherence.Schema

  schema "users" do
    field :name, :string
    field :email, :string
    field :role, :string
    field :invitation_list, :string
    field :team_id, :integer
    coherence_schema

    has_many :events, RoomPlz.Event
    has_many :event_logs, RoomPlz.EventLog
    belongs_to :branch, RoomPlz.Branch

    timestamps
  end

  def changeset(model, params \\ %{}) do
    params = add_default_role(model, params)

    model
    |> cast(params, [:name, :email, :role, :branch_id, :invitation_list, :team_id] ++ coherence_fields)
    |> validate_required([:name, :email])
    |> validate_format(:email, ~r/@framgia.com/, [message: "requires Framgia email"])
    |> unique_constraint(:email)
    |> validate_coherence(params)
  end

  def changeset(model, params, :password) do
    model
    |> cast(params, [:password, :password_confirmation, :reset_password_token, :reset_password_sent_at])
    |> validate_coherence_password_reset(params)
  end

  defp add_default_role(_model, %{"role" => _role} = params) do
    params
  end

  defp add_default_role(model, params) when model == %RoomPlz.User{} do
    Map.merge(params, %{"role" => "member"})
  end

  defp add_default_role(_model, params) do
    params
  end

  def is_admin?(model) do
    model && (model.role == "admin" || model.role == "super-admin")
  end

  def is_super_admin?(model) do
    model && model.role == "super-admin"
  end

  def is_owner(id1, id2) do
    id1 == id2
  end

  def is_collaborator(user_id, collaborators) do
    Enum.any?(collaborators, fn collaborator_id -> user_id == collaborator_id end)
  end

  def all_for_select do
    RoomPlz.User
    |> ModelHelpers.sort_by_email
    |> Repo.all
    |> ModelHelpers.options_for_select(:email, :id)
  end

  def is_edit_page(conn) do
    String.contains?(conn.request_path, "edit")
  end

  def list_roles(user) do
    cond do
      is_super_admin?(user) -> ["member", "admin", "super-admin"]
      is_admin?(user) -> ["member", "admin"]
      true -> ["member"]
    end
  end

  def show_emails(nil) do
    %{}
  end

  def show_emails(lists) do
    lists
    |> String.split(",")
    |> Enum.map(fn email -> Repo.get_by(RoomPlz.User, %{email: email}) end)
    |> Enum.map(fn user -> user.email end)
  end
end

web/controllers/user_controller.ex
defmodule RoomPlz.UserController do
  use RoomPlz.Web, :controller
  alias RoomPlz.{User, Event, ModelHelpers, Team}
  alias Coherence.Config

  plug :load_and_authorize_resource, model: User, except: [:user_requests]
  plug :is_same_user, %{} when action in [:user_requests]
  plug :get_teams when action in [:new, :create, :edit, :update]

  def index(conn, _params) do
    users =
      User
      |> Repo.all()
      |> Repo.preload(:branch)
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, user_params)

    case Repo.insert(changeset) do
      {:ok, user} ->
        # confirm users if users are created by admin
        if String.contains?(conn.request_path, "users") do
          Coherence.ControllerHelpers.confirm!(user)
        end

        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: user_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user =
      User
      |> Repo.get!(id)
      |> Repo.preload(:branch)

    invitation_list = if user.invitation_list, do: Regex.replace(~r/,/, user.invitation_list, ", "), else: ""
    user = Map.merge(user, %{invitation_list: invitation_list})
    team = if user.team_id, do: Repo.get(Team, user.team_id), else: %{name: ""}

    render(conn, "show.html", user: user, team: team)
  end

  def edit(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    current_user = conn.assigns.current_user
    changeset = User.changeset(user)
    is_owner = user.id == current_user.id
    render(conn, "edit.html", user: user, changeset: changeset, is_owner: is_owner)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    current_user = conn.assigns.current_user
    user = Repo.get!(User, id)
    is_owner = user.id == current_user.id

    changeset =
      # prevent normal users from changing role or email fields
      if is_authorized(current_user, user_params) do
        User.changeset(user, user_params)
      else
        {:unauthorized}
      end

    if changeset == {:unauthorized} do
      redirect_with_error(conn)
    else
      case Repo.update(changeset) do
        {:ok, user} ->
          if user.id == conn.assigns.current_user.id do
            apply(Config.auth_module, Config.update_login, [conn, user, [id_key: Config.schema_key]])
          end

          conn
          |> put_flash(:info, "User updated successfully.")
          |> redirect(to: user_path(conn, :show, user))
        {:error, changeset} ->
          render(conn, "edit.html", user: user, changeset: changeset, is_owner: is_owner)
      end
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Repo.get!(User, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end

  def user_requests(conn, %{"user_id" => user_id} = params) do
    events =
      Event
      |> ModelHelpers.sort_by_id()
      |> ModelHelpers.with_limit(params)
      |> Repo.all()
      |> Repo.preload([:creator, room: :branch])
      |> Enum.filter(&is_user(&1, conn.assigns.current_user))

    render(conn, "user_requests.html", events: events, user_id: user_id)
  end

  def is_same_user(conn, _opts) do
    user = Repo.get!(User, conn.params["user_id"])
    current_user = conn.assigns.current_user
    if current_user.id == user.id do
      conn
    else
      redirect_with_error(conn)
    end
  end

  defp is_authorized(current_user, user_params) do
    User.is_super_admin?(current_user) ||
    (current_user.role == user_params["role"] && current_user.email == user_params["email"])
  end

  defp is_user(event, user) do
    collaborators = if event.collaborators, do: String.split(event.collaborators, ","), else: []
    user.id == event.creator.id || Enum.any?(collaborators, fn x -> x == user.email end)
  end
end

web/views/user_view.ex
defmodule RoomPlz.UserView do
  use RoomPlz.Web, :view
end

web/templates/user/edit.html.eex
<h2>Edit user</h2>

<%= render "form.html", changeset: @changeset, current_user: @current_user, conn: @conn,
                        is_owner: @is_owner, action: user_path(@conn, :update, @user) %>

<%= link "Back", to: user_path(@conn, :index) %>

web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= required_label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= required_label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control", disabled: true %>
    <%= error_tag f, :email %>
  </div>

  <div class="password-field <%= if RoomPlz.User.is_edit_page(@conn), do: 'hidden'%>">
    <div class="form-group">
      <%= required_label f, :current_password, class: "control-label" %>
      <%= password_input f, :current_password, class: "form-control password disabled", disabled: RoomPlz.User.is_edit_page(@conn) %>
      <%= error_tag f, :current_password %>
    </div>

    <div class="form-group">
      <%= required_label f, :password, class: "control-label" %>
      <%= password_input f, :password, class: "form-control password disabled", disabled: RoomPlz.User.is_edit_page(@conn) %>
      <%= error_tag f, :password %>
    </div>

    <div class="form-group">
    <%= required_label f, :password_confirmation, class: "control-label" %>
      <%= password_input f, :password_confirmation, class: "form-control password disabled",
        disabled: RoomPlz.User.is_edit_page(@conn) %>
      <%= error_tag f, :password_confirmation %>
    </div>
  </div>

  <div class="form-group">
    <%= label f, :role, class: "control-label" %>
    <%= select f, :role, RoomPlz.User.list_roles(@current_user), class: "form-control",
                  disabled: !RoomPlz.User.is_super_admin?(@current_user) && !@is_owner %>
    <%= error_tag f, :role %>
  </div>

  <div class="form-group">
    <%= label f, :default_branch, class: "control-label" %>
    <select name="user[branch_id]" class="selectpicker form-control" id="branch-picker">
      <%= for {name, id} <- RoomPlz.Branch.all_for_select(@current_user) do %>
      <option value="<%= id %>"><%= name %></option>
      <%= end %>
    </select>
  </div>

  <div class="form-group">
    <%= label f, :invitation_suggestion, class: "control-label" %>
    <%= text_input f, :invitation_list, class: "form-control", id: "invitations" %>
    <%= error_tag f, :invitation_list %>
  </div>

  <div class="form-group">
    <%= label f, :default_team, class: "control-label" %>
    <%= select f, :team_id, @conn.assigns.teams, prompt: "Choose your team", class: "form-control" %>
    <%= error_tag f, :team_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary", id: "user-edit" %>

    <%= if RoomPlz.User.is_edit_page(@conn) && @is_owner do %>
    <a class="btn btn-warning" id="password-edit">Toggle password</a>
    <%= end %>
  </div>
<% end %>

web/templates/user/index.html.eex
<h2>Listing users</h2>

<table class="table" id="search-table">
  <thead class="table-header">
    <tr>
      <th>Name <i class="fa fa-sort" aria-hidden="true"></i></th>
      <th>Email <i class="fa fa-sort" aria-hidden="true"></i></th>
      <th>Role <i class="fa fa-sort" aria-hidden="true"></i></th>
      <th>Default Branch <i class="fa fa-sort" aria-hidden="true"></i></th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.role %></td>
      <td><%= if user.branch, do: user.branch.name, else: "" %></td>

      <td class="text-right">
        <%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New user", to: user_path(@conn, :new) %>

web/templates/user/new.html.eex
<h2>New user</h2>

<%= render "form.html", changeset: @changeset, current_user: @current_user, conn: @conn,
                        action: user_path(@conn, :create) %>

<%= link "Back", to: user_path(@conn, :index) %>

web/templates/user/scripts.edit.html.eex
<script src="<%= static_path(@conn, "/js/helpers.js") %>"></script>
<script src="<%= static_path(@conn, "/js/event.js") %>"></script>

web/templates/user/show.html.eex
<h2 style="margin-bottom: 20px">Show user</h2>

<table class="table table-hover">
  <tr>
    <td><strong><i class="fa fa-user-o"></i> Name:</strong></td>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <td><strong><i class="fa fa-envelope-o"></i> Email:</strong></td>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <td><strong><i class="fa fa-address-card"></i> Role:</strong></td>
    <td><%= @user.role %></td>
  </tr>
  <tr>
    <td><strong><i class="fa fa-building-o"></i> Default Branch:</strong></td>
    <td><%= if @user.branch, do: @user.branch.name, else: "" %></td>
  </tr>
  <tr>
    <td><strong><i class="fa fa-users" aria-hidden="true"></i> Default Team:</strong></td>
    <td><%= @team.name %></td>
  </tr>
  <tr>
    <td><strong><i class="fa fa-list" aria-hidden="true"></i> Invitation Suggestion:</strong></td>
    <td><%= @user.invitation_list %></td>
  </tr>
</table>

<%= link "Edit", to: user_path(@conn, :edit, @user), class: "btn btn-primary", style: "margin-right: 5px" %>
<%= link "Back", to: user_path(@conn, :index), class: "btn btn-primary" %>

web/templates/user/user_requests.html.eex
<h2>Listing user event requests</h2>

<hr>
<div>
    <div class="form-group row">
        <label class="control-label col-sm-2">
            All events
            <span class="badge" data-toggle="tooltip" data-placement="top" title="By default, only 150 recent events are shown">?</span>
            :
        </label>
        <%= link "Show All Events", to: user_user_path(@conn, :user_requests, @user_id, show: "all"), class: "btn btn-success col-sm-2" %>
    </div>
</div>

<hr>
<table class="table" id="search-table">
    <thead class="table-header">
    <tr>
        <th>ID <i class="fa fa-sort" aria-hidden="true"></i></th>
        <th>Title <i class="fa fa-sort" aria-hidden="true"></i></th>
        <th>Collaborators <i class="fa fa-sort" aria-hidden="true"></i></th>
        <th>Branch <i class="fa fa-sort" aria-hidden="true"></i></th>
        <th>Room <i class="fa fa-sort" aria-hidden="true"></i></th>
        <th>Start <i class="fa fa-sort" aria-hidden="true"></i></th>
        <th>End <i class="fa fa-sort" aria-hidden="true"></i></th>
        <th>Repeat <i class="fa fa-sort" aria-hidden="true"></i></th>
        <th>Status <i class="fa fa-sort" aria-hidden="true"></i></th>

        <th></th>
    </tr>
    </thead>
    <tbody>
    <%= for event <- @events do %>
    <tr>
        <td><%= event.id %></td>
        <td><%= event.title %></td>
        <td>
            <%= if event.collaborators do %>
            <select class="selectpicker" data-width="150px">
                <%= for email <- RoomPlz.User.show_emails(event.collaborators) do %>
                <option><%= email %></option>
                <%= end %>
            </select>
            <%= end %>
        </td>
        <td><%= event.room.branch.name %></td>
        <td><%= event.room.name %></td>
        <td><%= RoomPlz.Tools.ecto_to_local_datetime(event.start, :datetime_str) %></td>
        <td><%= RoomPlz.Tools.ecto_to_local_datetime(event.end, :datetime_str) %></td>
        <td><%= event.repeat %></td>
        <td><%= String.capitalize(event.status) %></td>

        <td class="text-right" style="width: 250px">
            <%= Phoenix.View.render RoomPlz.EventView, "action.html", %{conn: @conn, event: event, branch: event.room.branch.id} %>

            <%= link "Edit", to: branch_event_path(@conn, :edit, event.room.branch.id, event), class: "btn btn-primary btn-xs" %>

            <%= link "Show", to: branch_event_path(@conn, :show, event.room.branch.id, event), class: "btn btn-primary btn-xs" %>
        </td>
    </tr>
    <% end %>
    </tbody>
</table>