web/router.ex
defmodule RoomPlz.Router do
  use RoomPlz.Web, :router
  use Coherence.Router
  alias RoomPlz.Branch

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
    plug :get_other_branches
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
    plug :get_other_branches
  end

  scope "/" do
    pipe_through :browser
    coherence_routes
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug Coherence.Authentication.Session
  end

  pipeline :api_protected do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
  end

  scope "/", RoomPlz do
    pipe_through :protected # protected resources

    resources "/users", UserController do
      get "/requests", UserController, :user_requests
    end

    resources "/branches", BranchController do
      resources "/events", EventController
      resources "/rooms", RoomController
    end
    get "/event_logs", EventLogController, :index

    # Car Booking
    resources "/cars", CarController
    get "/car_logs", CarController, :show_car_logs

    resources "/slots", SlotController, except: [:show]
    get "/slot_logs", SlotLogController, :index

    # Authorization
    get "/auth/google", AuthController, :gg_authenticate
    get "/auth/google/callback", AuthController, :gg_callback
    delete "/auth/google", AuthController, :gg_delete

  end

  scope "/", RoomPlz do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/teams", TeamController
    get"/slots/:id", SlotController,  :show
    get "/rooms/suggestion", RoomController, :suggestion

    resources "/branches", BranchController, only: [:show] do
      get "/calendar", CalendarController, :index
    end
    # Car Booking
    get "/car_calendar", CarController, :show_car_calendar

    # Authorization
    get "/auth/wsm", AuthController, :wsm_authenticate
    get "/auth/wsm/callback", AuthController, :wsm_callback
  end

  scope "/api", RoomPlz do
    pipe_through :api

    get "/rooms", APIController, :rooms
    get "/branches/:id", APIController, :show_branch
    get "/suggestion", APIController, :suggestion

    # Car Booking
    get "/cars", APIController, :cars
    get "/slots", APIController, :slots
    get "/slot/:id", APIController, :get_slot
  end

  scope "/api", RoomPlz do
    pipe_through :api_protected

    get "/users", APIController, :users
    get "/users/:id", APIController, :get_invitation_list
    post "/events/synchronize", APIController, :synchronize
    post "/import_events", APIController, :import_events
  end

  defp get_other_branches(conn, _params) do
    branch_id = if conn.params["branch_id"], do: String.to_integer(conn.params["branch_id"])
    assign(conn, :other_branches, Branch.get_other_branches(branch_id))
  end
end

web/views/coherence/layout_view.ex
defmodule Coherence.LayoutView do
  use Phoenix.View, root: "web/templates"
  # Import convenience functions from controllers
  import Phoenix.Controller, only: [get_flash: 2]

  # Use all HTML functionality (forms, tags, etc)
  use Phoenix.HTML

  import RoomPlz.Router.Helpers
end

web/views/layout_view.ex
defmodule RoomPlz.LayoutView do
  use RoomPlz.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta content="<%= Plug.CSRFProtection.get_csrf_token %>" name="token" />

    <title>Room Plz!</title>

    <link rel="icon" href="<%= static_path(@conn, "/images/calendar_icon.jpg") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/font-awesome.css") %>">
    <%= render_existing(@view_module, "meta." <> @view_template, assigns) || render(RoomPlz.LayoutView, "meta.html", assigns) %>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>

    <div id="loading">
    <img id="loading-image" src="https://s-media-cache-ak0.pinimg.com/originals/f0/fc/99/f0fc99947787440ab8dd23c424834f59.gif" alt="Loading..." />
    </div>

    <div class="container-fluid" id="container">
        <nav class="navbar navbar-library">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a href="/">
                <img id="logo" class="pull-left" src="<%= static_path(@conn, "/images/framgia_logo.png") %>" alt="Framgia Logo">
            </a>
            <ul class="nav navbar-nav navbar-left">
                <li><a href="/">Home</a></li>
                <li><a href="https://goo.gl/Gi1Dpc" target="_blank">FAQs</a></li>
                <li><a href="https://goo.gl/forms/SaaD4e4pHhDiN9Y12" target="_blank">Feedback</a></li>
            </ul>
        </div>
		<div class="collapse navbar-collapse" id="navbar">
			<ul class="nav navbar-nav navbar-right">
                <%= if assigns[:current_user] do %>
                    <li class="top-nav dropdown">
                        <a class="dropdown-toggle top-nav" id="nav-branch" data-toggle="dropdown" role="button">
                            <span id="top-nav-branch"></span>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <%= for other_branch <- @conn.assigns.other_branches do %>
                            <li><a href="<%= RoomPlz.Branch.get_link(@conn, other_branch.id) %>"><%= other_branch.name %></a></li>
                            <%= end %>
                        </ul>
                    </li>
                    <li><a class="top-nav top-nav-calendar">Calendar</a></li>
                    <li id="my-events"><a href="/users/<%= @current_user.id %>/requests">My Events</a></li>
                <%= end %>
				<li class="dropdown" id="nav-dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                        <%= if Coherence.logged_in?(@conn) do %>
                        <%= Coherence.current_user(@conn).name %>
                        <% else %>
                        Hello, Guest
                        <% end %>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <%= if Coherence.logged_in?(@conn) do %>
                            <li><%= link "Profile", to: user_path(@conn, :show, @current_user) %></li>
                            <%= if RoomPlz.User.is_admin?(@current_user) do %>
                            <li class="top-nav dropdown manage">
                                <a class="dropdown-toggle top-nav" data-toggle="dropdown" role="button">Manage <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><%= link " Users", to: user_path(@conn, :index) %></li>
                                    <li><%= link " Teams", to: team_path(@conn, :index) %></li>
                                    <li><a href="/branches">Branches</a></li>
                                    <li><a class="top-nav top-nav-rooms">Rooms</a></li>
                                    <li><a class="top-nav top-nav-events">Events</a></li>
                                </ul>
                            </li>
                            <%= end %>

                            <%= form_for @conn, session_path(@conn, :delete), [as: :logout, method: :delete, id: "logout"], fn _ -> %>
                            <%= submit "Logout" %>
                            <% end %>
                            <input id="user-id" value="<%= @current_user.id %>" hidden>
                            <input id="user-role" value="<%= @current_user.role %>" hidden>
                            <input id="user-default-branch" value="<%= @current_user.branch_id %>" hidden>
                        <% else %>
                            <li><%= link "Login", to: session_path(@conn, :new) %></li>
                            <li><%= link "Registration", to: registration_path(@conn, :new) %></li>
                        <% end %>
					</ul>
				</li>
			</ul>
		</div>
      </nav>
    </div>

    <div class="container" id="main">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <div class="row clearfix">
        <%= render @view_module, @view_template, assigns %>
        </div>
      </main>
      <footer>
        <div class="col-lg-offset-9 col-md-offset-9 col-lg-4 col-md-6">
          © Framgia Vietnam <%= DateTime.utc_now.year %> - R&D Lab
        </div>
      </footer>
    </div> <!-- /container -->

    <script>window.userToken = "<%= assigns[:user_token] %>"</script>
    <script src="<%= static_path(@conn, "/js/config.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <%= render_existing(@view_module, "scripts." <> @view_template, assigns) %>
  </body>
</html>

web/templates/layout/email.html.eex
<html>
  <head>
    <title><%= @email.subject %></title>
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>