web/router.ex
defmodule RoomPlz.Router do
  use RoomPlz.Web, :router
  use Coherence.Router
  alias RoomPlz.Branch

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
    plug :get_other_branches
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
    plug :get_other_branches
  end

  scope "/" do
    pipe_through :browser
    coherence_routes
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug Coherence.Authentication.Session
  end

  pipeline :api_protected do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
  end

  scope "/", RoomPlz do
    pipe_through :protected # protected resources

    resources "/users", UserController do
      get "/requests", UserController, :user_requests
    end

    resources "/branches", BranchController do
      resources "/events", EventController
      resources "/rooms", RoomController
    end
    get "/event_logs", EventLogController, :index

    # Car Booking
    resources "/cars", CarController
    get "/car_logs", CarController, :show_car_logs

    resources "/slots", SlotController, except: [:show]
    get "/slot_logs", SlotLogController, :index

    # Authorization
    get "/auth/google", AuthController, :gg_authenticate
    get "/auth/google/callback", AuthController, :gg_callback
    delete "/auth/google", AuthController, :gg_delete

  end

  scope "/", RoomPlz do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/teams", TeamController
    get"/slots/:id", SlotController,  :show
    get "/rooms/suggestion", RoomController, :suggestion

    resources "/branches", BranchController, only: [:show] do
      get "/calendar", CalendarController, :index
    end
    # Car Booking
    get "/car_calendar", CarController, :show_car_calendar

    # Authorization
    get "/auth/wsm", AuthController, :wsm_authenticate
    get "/auth/wsm/callback", AuthController, :wsm_callback
  end

  scope "/api", RoomPlz do
    pipe_through :api

    get "/rooms", APIController, :rooms
    get "/branches/:id", APIController, :show_branch
    get "/suggestion", APIController, :suggestion

    # Car Booking
    get "/cars", APIController, :cars
    get "/slots", APIController, :slots
    get "/slot/:id", APIController, :get_slot
  end

  scope "/api", RoomPlz do
    pipe_through :api_protected

    get "/users", APIController, :users
    get "/users/:id", APIController, :get_invitation_list
    post "/events/synchronize", APIController, :synchronize
    post "/import_events", APIController, :import_events
  end

  defp get_other_branches(conn, _params) do
    branch_id = if conn.params["branch_id"], do: String.to_integer(conn.params["branch_id"])
    assign(conn, :other_branches, Branch.get_other_branches(branch_id))
  end
end

web/models/slot.ex
defmodule RoomPlz.Slot do
  use RoomPlz.Web, :model
  import RoomPlz.{ModelHelpers, EventView}
  alias RoomPlz.Car

  schema "slots" do
    field :title, :string
    field :start, Ecto.DateTime
    field :end, Ecto.DateTime
    field :status, :string
    field :description, :string
    field :utilizer, :string
    field :driver, :string
    field :invitation, :string

    belongs_to :creator, RoomPlz.User
    belongs_to :car, RoomPlz.Car
    has_many :slot_logs, RoomPlz.SlotLog
    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :start, :end, :status, :description, :utilizer, :driver, :invitation, :creator_id, :car_id])
    |> validate_required([:title, :start, :end, :status, :utilizer, :driver, :creator_id, :car_id])
    |> validate_duration
    |> check_available
    |> change_title
  end

  defp validate_duration(changeset) do
    start_time = get_field(changeset, :start)
    end_time = get_field(changeset, :end)

    case Ecto.DateTime.compare(start_time, end_time) do
      :lt -> changeset
      _ -> add_error(changeset, :duration, "Start time must before end time")
    end
  end

  defp check_available(%{:valid? => true} = changeset) do
    start_time = get_field(changeset, :start)
    end_time = get_field(changeset, :end)
    car_id = get_field(changeset, :car_id)
    id = get_field(changeset, :id)

    overlap_slots =
      RoomPlz.Slot
      |> same_car_id(car_id)
      |> not_id(id)
      |> is_status("approved")
      |> is_overlapped(start_time, end_time)
      |> Repo.all

    case overlap_slots do
      [head | _tail] ->
        add_error(changeset, :overlap, "Overlap with one or more slots,
          for example: #{head.title} on #{Map.get(head, "same_date")}
          from #{get_time(head.start)} ~ #{get_time(head.end)}")
      [] ->
        changeset
    end
  end

  defp check_available(%{:valid? => false} = changeset) do
    changeset
  end

  def same_car_id(query, car_id) do
    from s in query,
         where: s.car_id == ^car_id
  end

  defp change_title(%{:valid? => true} = changeset) do
    car_id = get_field(changeset, :car_id)
    title = get_field(changeset, :title)
    car = Repo.get!(Car, car_id)
    added_car = "[#{car.name}] "
    new_title = added_car <> title

    if String.contains?(title, added_car) do
      changeset
    else
      put_change(changeset, :title, new_title)
    end
  end

  defp change_title(%{:valid? => false} = changeset) do
    changeset
  end

  # Change slot title when car change name
  def change_all_titles(car, new_car_name) do
    RoomPlz.Slot
    |> with_car
    |> from_car(car)
    |> Repo.all
    |> Enum.each(&change_slot_title(&1, new_car_name))
  end

  defp change_slot_title(slot, new_car_name) do
    new_title =
      ~r/\[(.*)\]/
      |> Regex.replace(slot.title, "[#{new_car_name}]")

    slot
    |> cast(%{"title" => new_title}, [:title])
    |> Repo.update()
  end

  def with_car(query) do
    query
    |> join(:inner, [s], c in assoc(s, :car))
  end

  def from_car(query, car) do
    query
    |> where([s, c], c.id == ^car.id)
  end
end

web/controllers/slot_controller.ex
defmodule RoomPlz.SlotController do
  use RoomPlz.Web, :controller
  alias RoomPlz.{Slot, SlotLogController, Email}

  def index(conn, _params) do
    slots =
      Slot
      |> Repo.all()
      |> Repo.preload([:creator, :car])

    render(conn, "index.html", slots: slots)
  end

  def new(conn, _params) do
    changeset = Slot.changeset(%Slot{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"slot" => slot_params}) do
    slot_params = convert_slot_time(slot_params)
    changeset = Slot.changeset(%Slot{}, slot_params)

    case Repo.insert(changeset) do
      {:ok, slot} ->
        create_log(slot, conn, slot_params["action"])
        send_email(slot, "created")

        render(conn, RoomPlz.ChangesetView, "event_success.json", success: "Create slot successfully")
      {:error, changeset} ->
        render(conn, RoomPlz.ChangesetView, "error.json", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    slot =
      Slot
      |> Repo.get!(id)
      |> Repo.preload([:creator, :car, slot_logs: :user])

    render(conn, "show.html", slot: slot)
  end

  def edit(conn, %{"id" => id}) do
    slot = Repo.get!(Slot, id)
    changeset = Slot.changeset(slot)
    render(conn, "edit.html", slot: slot, changeset: changeset)
  end

  def update(conn, %{"id" => id, "slot" => %{"start_time" => _} = slot_params}) do
    slot_params = convert_slot_time(slot_params)

    changeset =
      Slot
      |> Repo.get!(id)
      |> Slot.changeset(slot_params)

    case Repo.update(changeset) do
      {:ok, slot} ->
        create_log(slot, conn, slot_params["action"])
        send_email(slot, "updated")

        render(conn, RoomPlz.ChangesetView, "event_success.json", success: "Update slot successfully")
      {:error, changeset} ->
        render(conn, RoomPlz.ChangesetView, "error.json", changeset: changeset)
    end
  end

  # Update event status
  def update(conn, %{"id" => id, "slot" =>  %{"status" => updated_status} = params}) do
    slot = Repo.get!(Slot, id)

    slot
    |> Slot.changeset(%{status: updated_status})
    |> Repo.update!
    |> send_email("updated")

    create_status_log(conn, slot, updated_status)


    if params["form_type"] == "form" do
      conn
      |> put_flash(:info, "The slot was #{updated_status}")
      |> redirect(to: car_path(conn, :show_car_calendar))
    else
      render(conn, RoomPlz.ChangesetView, "event_success.json", success: "#{String.capitalize(updated_status)} slot successfully")
    end
  end

  def delete(conn, %{"id" => id}) do
    slot = Repo.get!(Slot, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(slot)

    conn
    |> put_flash(:info, "Slot deleted successfully.")
    |> redirect(to: slot_path(conn, :index))
  end

  def create_log(slot, conn, action) do
    date = ecto_to_local_datetime(slot.start, :date_str)
    start_time = ecto_to_local_datetime(slot.start, :shorten_time_str)
    end_time = ecto_to_local_datetime(slot.end, :shorten_time_str)

    detail = "#{date}: from #{start_time} to #{end_time}"
    slot = %{
      action: String.upcase(action),
      detail: detail,
      utilizer: slot.utilizer,
      driver: slot.driver,
      user_id: conn.assigns.current_user.id,
      slot_id: slot.id
    }

    SlotLogController.create(slot)
  end

  def create_status_log(conn, slot, updated_status) do
    log = %{
      action: String.upcase(updated_status),
      detail: "Change status from #{slot.status} to #{updated_status}",
      utilizer: slot.utilizer,
      driver: slot.driver,
      slot_id: slot.id,
      user_id: conn.assigns.current_user.id
    }
    SlotLogController.create(log)
  end

  def send_email(slot, action) do
    if slot.invitation do
      slot.invitation
      |> String.split(",")
      |> Enum.each(&Email.send_notification_email(&1, slot, action))
    end
  end

  def convert_slot_time(params) do
    Map.merge(params, %{"start" => date_str_to_datetime(params["start_time"], :utc),
                        "end" => date_str_to_datetime(params["end_time"], :utc)})
  end
end

web/views/slot_view.ex
defmodule RoomPlz.SlotView do
  use RoomPlz.Web, :view
end

web/templates/slot/index.html.eex
<h2>Listing slots</h2>
<hr>
<div>
  <div class="form-group branch-selection row">
    <label class="control-label col-sm-2">Event Logs: </label>
    <%= link "Show all logs", to: slot_log_path(@conn, :index), class: "btn btn-success col-sm-2" %>
  </div>
</div>

<hr>
<table class="table" id="search-table">
  <thead>
    <tr>
      <th>Title <i class="fa fa-sort" aria-hidden="true"></i></th>
      <th>Start <i class="fa fa-sort" aria-hidden="true"></i></th>
      <th>End <i class="fa fa-sort" aria-hidden="true"></i></th>
      <th>Status <i class="fa fa-sort" aria-hidden="true"></i></th>
      <th>Description <i class="fa fa-sort" aria-hidden="true"></i></th>
      <th>Utilizer <i class="fa fa-sort" aria-hidden="true"></i></th>
      <th>Driver <i class="fa fa-sort" aria-hidden="true"></i></th>
      <th>Creator <i class="fa fa-sort" aria-hidden="true"></i></th>
      <th>Car <i class="fa fa-sort" aria-hidden="true"></i></th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for slot <- @slots do %>
    <tr>
      <td><%= slot.title %></td>
      <td><%= slot.start %></td>
      <td><%= slot.end %></td>
      <td><%= slot.status %></td>
      <td><%= slot.description %></td>
      <td><%= slot.utilizer %></td>
      <td><%= slot.driver %></td>
      <td><%= slot.creator.name %></td>
      <td><%= slot.car.name %></td>

      <td class="text-right">
        <%= form_for @conn, slot_path(@conn, :update, slot),
        [as: :slot, style: "display: inline-block; margin: 0"], fn f -> %>
          <input name="_method" type="hidden" value="PUT">
          <%= text_input f, :form_type, hidden: true, value: "form" %>
          <%= text_input f, :status, hidden: true, value: "approved" %>
          <div class="form-group">
            <%= submit "Approve", class: RoomPlz.Event.get_class(slot.status, :approved),
            disabled: slot.status == "approved" %>
          </div>
        <%= end %>

        <%= form_for @conn, slot_path(@conn, :update, slot),
        [as: :slot, style: "display: inline-block; margin: 0"], fn f -> %>
          <input name="_method" type="hidden" value="PUT">
        <%= text_input f, :form_type, hidden: true, value: "form" %>
          <%= text_input f, :status, hidden: true, value: "rejected" %>
          <div class="form-group">
            <%= submit "Reject", class: RoomPlz.Event.get_class(slot.status, :rejected),
            disabled: slot.status == "rejected" %>
          </div>
        <%= end %>

        <%= link "Show", to: slot_path(@conn, :show, slot), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: slot_path(@conn, :edit, slot), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: slot_path(@conn, :delete, slot), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

web/templates/slot/show.html.eex
<h2>Show slot</h2>

<ul>

  <li>
    <strong>ID:</strong>
    <%= @slot.id %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @slot.title %>
  </li>

  <li>
    <strong>Start:</strong>
    <%= @slot.start %>
  </li>

  <li>
    <strong>End:</strong>
    <%= @slot.end %>
  </li>

  <li>
    <strong>Status:</strong>
    <%= @slot.status %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @slot.description %>
  </li>

  <li>
    <strong>Utilizer:</strong>
    <%= @slot.utilizer %>
  </li>

  <li>
    <strong>Driver:</strong>
    <%= @slot.driver %>
  </li>

  <li>
    <strong>Creator:</strong>
    <%= @slot.creator.name %>
  </li>

  <li>
    <strong>Car:</strong>
    <%= @slot.car.name %>
  </li>

</ul>

<table class="table" id="search-table">
  <thead class="table-header">
  <tr>
    <th>Action <i class="fa fa-sort" aria-hidden="true"></th>
    <th>Detail <i class="fa fa-sort" aria-hidden="true"></th>
    <th>Creator <i class="fa fa-sort" aria-hidden="true"></th>
    <th>Utilizer <i class="fa fa-sort" aria-hidden="true"></th>
    <th>Driver <i class="fa fa-sort" aria-hidden="true"></th>
    <th>Created at <i class="fa fa-sort" aria-hidden="true"></th>
  </tr>
  </thead>
  <tbody>
  <%= for slot_log <- @slot.slot_logs do %>
  <tr>
    <td><%= slot_log.action %></td>
    <td><%= slot_log.detail %></td>
    <td><%= slot_log.user.name %></td>
    <td><%= slot_log.utilizer %></td>
    <td><%= slot_log.driver %></td>
    <td><%= RoomPlz.Tools.naive_to_local_datetime(slot_log.inserted_at, :datetime_str) %></td>
  </tr>
  <% end %>
  </tbody>
</table>

<%= link "Calendar", to: car_path(@conn, :show_car_calendar) %> &nbsp;
<%= link "Edit", to: slot_path(@conn, :edit, @slot) %> &nbsp;
<%= link "Back", to: slot_path(@conn, :index) %>