web/router.ex
defmodule RoomPlz.Router do
  use RoomPlz.Web, :router
  use Coherence.Router
  alias RoomPlz.Branch

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
    plug :get_other_branches
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
    plug :get_other_branches
  end

  scope "/" do
    pipe_through :browser
    coherence_routes
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug Coherence.Authentication.Session
  end

  pipeline :api_protected do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
  end

  scope "/", RoomPlz do
    pipe_through :protected # protected resources

    resources "/users", UserController do
      get "/requests", UserController, :user_requests
    end

    resources "/branches", BranchController do
      resources "/events", EventController
      resources "/rooms", RoomController
    end
    get "/event_logs", EventLogController, :index

    # Car Booking
    resources "/cars", CarController
    get "/car_logs", CarController, :show_car_logs

    resources "/slots", SlotController, except: [:show]
    get "/slot_logs", SlotLogController, :index

    # Authorization
    get "/auth/google", AuthController, :gg_authenticate
    get "/auth/google/callback", AuthController, :gg_callback
    delete "/auth/google", AuthController, :gg_delete

  end

  scope "/", RoomPlz do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/teams", TeamController
    get"/slots/:id", SlotController,  :show
    get "/rooms/suggestion", RoomController, :suggestion

    resources "/branches", BranchController, only: [:show] do
      get "/calendar", CalendarController, :index
    end
    # Car Booking
    get "/car_calendar", CarController, :show_car_calendar

    # Authorization
    get "/auth/wsm", AuthController, :wsm_authenticate
    get "/auth/wsm/callback", AuthController, :wsm_callback
  end

  scope "/api", RoomPlz do
    pipe_through :api

    get "/rooms", APIController, :rooms
    get "/branches/:id", APIController, :show_branch
    get "/suggestion", APIController, :suggestion

    # Car Booking
    get "/cars", APIController, :cars
    get "/slots", APIController, :slots
    get "/slot/:id", APIController, :get_slot
  end

  scope "/api", RoomPlz do
    pipe_through :api_protected

    get "/users", APIController, :users
    get "/users/:id", APIController, :get_invitation_list
    post "/events/synchronize", APIController, :synchronize
    post "/import_events", APIController, :import_events
  end

  defp get_other_branches(conn, _params) do
    branch_id = if conn.params["branch_id"], do: String.to_integer(conn.params["branch_id"])
    assign(conn, :other_branches, Branch.get_other_branches(branch_id))
  end
end

web/models/branch.ex
defmodule RoomPlz.Branch do
  use RoomPlz.Web, :model
  alias RoomPlz.{ModelHelpers, Room, Branch}

  schema "branches" do
    field :name, :string
    field :calendar_id, :string
    field :auth_email, :string
    field :refresh_token, :string

    has_many :rooms, Room
    has_many :event_logs, RoomPlz.EventLog

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :calendar_id, :auth_email, :refresh_token])
    |> validate_required([:name, :calendar_id])
  end

  defp except_the_current(query, nil) do
    query
  end

  defp except_the_current(query, branch_id) do
    from b in query,
    where: b.id != ^branch_id
  end

  defp sort_by_name(query) do
    from b in query,
    order_by: b.name
  end

  defp sort_default_branch(query, %{branch_id: branch_id} = _user) when not is_nil(branch_id) do
    from b in query,
    order_by: [desc: b.id == ^branch_id]
  end

  defp sort_default_branch(query, user) when is_nil(user) or is_map(user) do
    query
  end

  def all_for_select(user \\ %{}) do
    Branch
    |> sort_default_branch(user)
    |> sort_by_name()
    |> Repo.all
    |> ModelHelpers.options_for_select(:name, :id)
  end

  def default_branch_id(user \\ %{}) do
    default_branch_id =
      user
      |> Branch.all_for_select()
      |> Enum.map(&(elem(&1, 1)))
      |> List.first

    default_branch_id || 0
  end

  def get_other_branches(branch_id) do
    Branch
    |> except_the_current(branch_id)
    |> sort_by_name()
    |> Repo.all
    |> Enum.map(fn event -> %{id: event.id, name: event.name} end)
  end

  def get_link(conn, branch_id) do
    regex = ~r/\/branches\/(.*?)\//

    Regex.replace(regex, conn.request_path, "/branches/#{branch_id}/")
  end
end

web/controllers/branch_controller.ex
defmodule RoomPlz.BranchController do
  use RoomPlz.Web, :controller

  alias RoomPlz.{Branch, Room}
  plug :scrub_params, "branch" when action in [:create, :update]
  plug :load_and_authorize_resource, model: Branch

  @default_room %{"name" => "Other", "color" => "orange", "capacity" => 0, "overlap_acceptance" => true}

  def index(conn, _params) do
    branches = Repo.all(Branch)
    render(conn, "index.html", branches: branches)
  end

  def new(conn, _params) do
    changeset = Branch.changeset(%Branch{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"branch" => branch_params}) do
    changeset = Branch.changeset(%Branch{}, branch_params)

    case Repo.insert(changeset) do
      {:ok, branch} ->
        room = Map.merge(@default_room, %{"branch_id" => branch.id})

        %Room{}
        |> Room.changeset(room)
        |> Repo.insert()

        conn
        |> put_flash(:info, "Branch created successfully.")
        |> redirect(to: branch_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    branch = Repo.get!(Branch, id)
    render(conn, "show.html", branch: branch)
  end

  def edit(conn, _params) do
    changeset = Branch.changeset(conn.assigns.branch)
    render(conn, "edit.html", changeset: changeset)
  end

  def update(conn, %{"branch" => branch_params}) do
    changeset = Branch.changeset(conn.assigns.branch, branch_params)

    case Repo.update(changeset) do
      {:ok, branch} ->
        conn
        |> put_flash(:info, "Branch updated successfully.")
        |> redirect(to: branch_path(conn, :show, branch))
      {:error, changeset} ->
        render(conn, "edit.html", changeset: changeset)
    end
  end

  def delete(conn, _params) do
    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(conn.assigns.branch)

    conn
    |> put_flash(:info, "Branch deleted successfully.")
    |> redirect(to: branch_path(conn, :index))
  end
end

web/views/branch_view.ex
defmodule RoomPlz.BranchView do
  use RoomPlz.Web, :view
end

web/templates/branch/edit.html.eex
<h2>Edit branch</h2>

<%= render "form.html", changeset: @changeset,
                        action: branch_path(@conn, :update, @branch) %>

<%= link "Back", to: branch_path(@conn, :index) %>

web/templates/branch/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= required_label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= required_label f, "Calendar ID", class: "control-label" %>
    <%= text_input f, :calendar_id, class: "form-control" %>
    <%= error_tag f, :calendar_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/branch/index.html.eex
<h2>Listing branches</h2>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Calendar ID</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for branch <- @branches do %>
    <tr>
      <td><%= branch.id %></td>
      <td><%= branch.name %></td>
      <%= if RoomPlz.User.is_admin?(@current_user) do %>
        <td><%= branch.calendar_id %></td>
      <%= end %>
      <td class="text-right">
        <%= link "Calendar", to: branch_calendar_path(@conn, :index, branch), class: "btn btn-success btn-xs" %>
        <%= link "Rooms", to: branch_room_path(@conn, :index, branch), class: "btn btn-default btn-xs" %>
        <%= link "Events", to: branch_event_path(@conn, :index, branch), class: "btn btn-default btn-xs" %>
        <%= link "Show", to: branch_path(@conn, :show, branch), class: "btn btn-primary btn-xs" %>
        <%= link "Edit", to: branch_path(@conn, :edit, branch), class: "btn btn-primary btn-xs" %>
        <%= link "Delete", to: branch_path(@conn, :delete, branch), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= if RoomPlz.User.is_admin?(@current_user) do %>
  <%= link "New branch", to: branch_path(@conn, :new), class: "btn btn-primary" %>
  <btn class="btn btn-primary new-room" style="margin-left: 10px">New room</btn>
<%= end %>
<btn class="btn btn-primary new-event" style="margin-left: 5px">New event</btn>

<div class="branch-selection" hidden>
  <div class="form-group">
    <label class="control-label">Branch: </label>
    <select name="branch" class="selectpicker" id="branch-picker">
      <%= for {name, id} <- RoomPlz.Branch.all_for_select() do %>
          <option value="<%= id %>"><%= name %></option>
      <%= end %>
    </select>
    <%= link "Go", to: branch_event_path(@conn, :new, RoomPlz.Branch.default_branch_id()), class: "btn btn-success branch-new-event" %>
    <%= link "Go", to: branch_room_path(@conn, :new, RoomPlz.Branch.default_branch_id()), class: "btn btn-success branch-new-room" %>
  </div>
</div>

web/templates/branch/new.html.eex
<h2>New branch</h2>

<%= render "form.html", changeset: @changeset,
                        action: branch_path(@conn, :create) %>

<%= link "Back", to: branch_path(@conn, :index) %>

web/templates/branch/scripts.index.html.eex
<script src="<%= static_path(@conn, "/js/event.js") %>"></script>

web/templates/branch/show.html.eex
<h2>Show branch</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @branch.name %>
  </li>

  <li>
    <strong>Calendar ID:</strong>
    <%= @branch.calendar_id %>
  </li>

  <%= if RoomPlz.User.is_admin?(@current_user) do %>
  <li>
    <%= link "New room", to: branch_room_path(@conn, :new, @branch) %>
  </li>
  <%= end %>

  <li>
    <%= link "Show rooms", to: branch_room_path(@conn, :index, @branch) %>
  </li>

  <li>
    <%= link "Show events", to: branch_event_path(@conn, :index, @branch) %>
  </li>

  <li>
    <%= link "New event", to: branch_event_path(@conn, :new, @branch) %>
  </li>

</ul>

<%= link "Show Calendar", to: branch_calendar_path(@conn, :index, @branch), class: "btn btn-success" %> &nbsp;

<%= if RoomPlz.User.is_admin?(@current_user) do %>
<%= link "Edit", to: branch_path(@conn, :edit, @branch), class: "btn btn-primary" %> &nbsp;
<%= end %>

<%= link "Back", to: branch_path(@conn, :index), class: "btn btn-primary" %>